const vocabList = [
    { word: "Systematic", phonetic: "/ˌsɪstəˈmætɪk/", pos: "Adjective", meaning: "Done according to a plan.", example: "We need a systematic approach to data cleaning." },
    { word: "Prototype", phonetic: "/ˈprəʊtətaɪp/", pos: "Noun", meaning: "Early model of a product.", example: "The prototype failed the first test." },
    { word: "Assemble", phonetic: "/əˈsembl/", pos: "Verb", meaning: "Gather parts together.", example: "We assemble the raw data in the warehouse." },
    { word: "Integrated", phonetic: "/ˈɪntɪɡreɪtɪd/", pos: "Adjective", meaning: "Combined into a whole.", example: "The systems are fully integrated." },
    { word: "Capacity", phonetic: "/kəˈpæsəti/", pos: "Noun", meaning: "The maximum amount held.", example: "The server is at full capacity." },
    { word: "Efficient", phonetic: "/ɪˈfɪʃnt/", pos: "Adjective", meaning: "Working well without waste.", example: "This code is highly efficient." },
    { word: "Distribute", phonetic: "/dɪˈstrɪbjuːt/", pos: "Verb", meaning: "Share across a system.", example: "Data is distributed across nodes." },
    { word: "Evidence", phonetic: "/ˈevɪdəns/", pos: "Noun", meaning: "Information indicating truth.", example: "There is evidence of a breach." },
    { word: "Significant", phonetic: "/sɪɡˈnɪfɪkənt/", pos: "Adjective", meaning: "Important or large.", example: "A significant increase in traffic." },
    { word: "Analyze", phonetic: "/ˈænəlaɪz/", pos: "Verb", meaning: "Examine in detail.", example: "We analyze the trends in real-time." },
    { word: "Secure", phonetic: "/sɪˈkjʊər/", pos: "Adjective", meaning: "Fixed or protected.", example: "The connection must be secure." },
    { word: "Objective", phonetic: "/əbˈdʒektɪv/", pos: "Noun", meaning: "A goal or target.", example: "Our main objective is integrity." },
    { word: "Scalability", phonetic: "/ˌskeɪləˈbɪləti/", pos: "Noun", meaning: "Ability to handle growth.", example: "Scalability is crucial for growth." },
    { word: "Latency", phonetic: "/ˈleɪtənsi/", pos: "Noun", meaning: "Delay in data processing.", example: "We must reduce network latency." },
    { word: "Redundancy", phonetic: "/rɪˈdʌndənsi/", pos: "Noun", meaning: "Backup to avoid failure.", example: "Redundancy ensures data safety." },
    { word: "Throughput", phonetic: "/ˈθruːpʊt/", pos: "Noun", meaning: "Rate of data flow.", example: "The system has high throughput." },
    { word: "Automate", phonetic: "/ˈɔːtəmeɪt/", pos: "Verb", meaning: "Make a process automatic.", example: "We automate data pipelines." },
    { word: "Validation", phonetic: "/ˌvælɪˈdeɪʃn/", pos: "Noun", meaning: "Checking if data is correct.", example: "Validation prevents errors." },
    { word: "Infrastructure", phonetic: "/ˈɪnfrəstrʌktʃər/", pos: "Noun", meaning: "Underlying hardware/system.", example: "Cloud infrastructure is robust." },
    { word: "Vulnerable", phonetic: "/ˈvʌlnərəbl/", pos: "Adjective", meaning: "Open to risk or attack.", example: "Old systems are vulnerable." },
    { word: "Consistency", phonetic: "/kənˈsɪstənsi/", pos: "Noun", meaning: "Reliability of data.", example: "Consistency is vital for reports." },
    { word: "Deployment", phonetic: "/dɪˈplɔɪmənt/", pos: "Noun", meaning: "Putting software into use.", example: "The deployment was successful." },
    { word: "Optimization", phonetic: "/ˌɒptɪmaɪˈzeɪʃn/", pos: "Noun", meaning: "Making something better.", example: "Optimization improves speed." },
    { word: "Query", phonetic: "/ˈkwɪəri/", pos: "Noun", meaning: "Request for data.", example: "The query returned results." },
    { word: "Algorithm", phonetic: "/ˈælɡərɪðəm/", pos: "Noun", meaning: "Set of rules for tasks.", example: "The algorithm is complex." },
    { word: "Breakpoint", phonetic: "/ˈbreɪkpɔɪnt/", pos: "Noun", meaning: "Point of interruption.", example: "I set a breakpoint in code." },
    { word: "Concurrency", phonetic: "/kənˈkʌrənsi/", pos: "Noun", meaning: "Multiple tasks at once.", example: "Concurrency improves efficiency." },
    { word: "Dataset", phonetic: "/ˈdeɪtəsɛt/", pos: "Noun", meaning: "Collection of data.", example: "We cleaned the large dataset." },
    { word: "Encryption", phonetic: "/ɪnˈkrɪpʃn/", pos: "Noun", meaning: "Encoding information.", example: "Encryption protects our data." },
    { word: "Firewall", phonetic: "/ˈfaɪəwɔːl/", pos: "Noun", meaning: "Network security system.", example: "The firewall blocked access." },
    { word: "Interface", phonetic: "/ˈɪntəfeɪs/", pos: "Noun", meaning: "Point of interaction.", example: "The interface is user-friendly." },
    { word: "Middleware", phonetic: "/ˈmɪdlweər/", pos: "Noun", meaning: "Software between systems.", example: "Middleware connects the apps." }
];